-- LOGIN INTO POSTGRES
  -- 
  -- sudo -i -u postgres
  -- psql
  -- 
  -- sudo -u postgres
  -- psql -d mypgdatabase -U mypguser


CREATE TABLE users (
  user_id SERIAL PRIMARY KEY,
  telegram_id BIGINT UNIQUE NOT NULL,
  role_id INT NOT NULL CHECK (role_id IN (1, 2, 3)),
  name VARCHAR NOT NULL,
  username VARCHAR,
  location VARCHAR,
  city VARCHAR,
  email VARCHAR,
  phone VARCHAR,
  education VARCHAR,
  experience VARCHAR,
  cv VARCHAR,
  skills JSON,
  portfolios JSON,
  subscribed_alerts JSON,
  preferences JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE companies (
  company_id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(user_id),
  company_name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE jobs (
  job_id SERIAL PRIMARY KEY,
  company_id INTEGER REFERENCES companies(company_id),
  title TEXT NOT NULL,
  description TEXT,
  location VARCHAR,
  is_promoted BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE applications (
  application_id SERIAL PRIMARY KEY,
  job_id INTEGER REFERENCES jobs(job_id),
  user_id INTEGER REFERENCES users(user_id),
  status TEXT CHECK (status IN ('applied', 'shortlisted', 'rejected')) DEFAULT 'applied',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE saved_jobs (
  save_id SERIAL PRIMARY KEY,
  job_id INTEGER REFERENCES jobs(job_id),
  user_id INTEGER REFERENCES users(user_id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);














-- Generated by Codeium
CREATE TABLE alerts (
  alert_id SERIAL PRIMARY KEY,
  user_id INT NOT NULL,
  title VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);
CREATE TABLE user_alerts (
  user_alert_id SERIAL PRIMARY KEY,
  user_id INT NOT NULL,
  alert_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);
CREATE TABLE notifications (
  notification_id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(user_id),
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);
CREATE TABLE messages (
  message_id SERIAL PRIMARY KEY,
  sender_id INTEGER REFERENCES users(user_id),
  receiver_id INTEGER REFERENCES users(user_id),
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);
CREATE TABLE feedback (
  feedback_id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(user_id),
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);
CREATE TABLE reports (
  report_id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(user_id),
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);
CREATE TABLE settings (
  setting_id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(user_id),
  key VARCHAR NOT NULL,
  value VARCHAR NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);
